# use Ubuntu 14.04 (Trusty) image, it contains the latest JDK
sudo: required
dist: trusty

before_install:
  # start X-server for GUI tests (xvfb)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

language: java

jdk:
  - oraclejdk10
